2012-11-17 Factor out ok_grep_errors

diff --git a/bin/test-fns b/bin/test-fns
--- a/bin/test-fns
+++ b/bin/test-fns
@@ -17,3 +17,20 @@ fn ok_diff {
     }
     true
 }
+
+fn ok_grep_errors {
+    echo $1
+    if ($3 ./test-gslib ./test-gslib/$4 > ./test-results/$4^-actual >[2] ./test-results/$4^-errors) {
+        echo $3 'succeeded; should have failed' >[1=2]
+        cat ./test-results/$4^-errors >[1=2]
+        cat ./test-results/$4^-actual >[1=2]
+        exit 1
+    }
+    if (! grep -s $2 ./test-results/$4^-errors) {
+        echo 'Can''t find expected error message in output anywhere' >[1=2]
+        cat ./test-results/$4^-errors >[1=2]
+        cat ./test-results/$4^-actual >[1=2]
+        exit 1
+    }
+    true
+}
