2012-11-18 Factor out ok_diff_fail

diff --git a/bin/test-fns b/bin/test-fns
--- a/bin/test-fns
+++ b/bin/test-fns
@@ -18,6 +18,26 @@ fn ok_diff {
     true
 }
 
+fn ok_diff_fail {
+    echo $1
+    if ($2 ./test-gslib ./test-gslib/$3 > ./test-results/$3^-actual >[2] ./test-results/$3^-errors) {
+        echo $2 'succeeded; should have failed' >[1=2]
+        cat ./test-results/$3^-errors >[1=2]
+        cat ./test-results/$3^-actual >[1=2]
+        exit 1
+    }
+    if (! diff ./test-results/$3^-actual ./test-results/$3^-expected) {
+        echo $2 'produced incorrect output' >[1=2]
+        echo '--- Actual ---' >[1=2]
+        cat ./test-results/$3^-errors >[1=2]
+        cat ./test-results/$3^-actual >[1=2]
+        echo '--- Expected ---' >[1=2]
+        cat ./test-results/$3^-expected
+        exit 1
+    }
+    true
+}
+
 fn ok_grep_errors {
     echo $1
     if ($3 ./test-gslib ./test-gslib/$4 > ./test-results/$4^-actual >[2] ./test-results/$4^-errors) {
