[hsgs] Add assert ok_diff_compiled, for running compiled programs to test their output

diff --git a/bin/test-fns b/bin/test-fns
--- a/bin/test-fns
+++ b/bin/test-fns
@@ -250,6 +250,45 @@ fn ok_diff_compiler {
         do_exit
     }
     true
+}
+
+fn ok_diff_compiled {
+    nm=$1; cmd=$2; input=$3; outext=$4
+    shift; shift; shift; shift
+    runcmd=$*
+    setup_todo
+    echo $nm $todo_msg
+    output=`{echo $input | sed 's/\..*$/'^$outext^'/'}
+    if (! test -f ./test-fixtures/$input) {
+        echo $cmd $input ': no such file' ./test-fixtures/$input >[1=2]
+        do_exit
+    }
+    if (! test -f ./test-results/$cmd^-^$input^-expected) {
+        echo $cmd $input ': no such file' ./test-results/$cmd^-^$input^-expected >[1=2]
+        do_exit
+    }
+    if (! ./$cmd ./test-fixtures/$input > ./test-results/$cmd^-^$input^-errors >[2=1]) {
+        echo 'The command ' >[1=2]
+        echo '    ' $cmd ./test-fixtures/$input >[1=2]
+        echo 'failed; should have succeeded' >[1=2]
+        cat ./test-results/$cmd^-^$input^-errors
+        do_exit
+    }
+    if (! $runcmd ./test-fixtures/$output > ./test-results/$cmd^-^$input^-actual >[2] ./test-results/$cmd^-^$input^-errors) {
+        echo 'The command ' >[1=2]
+        echo '    ' $runcmd ./test-fixtures/$output >[1=2]
+        echo 'failed; should have succeeded' >[1=2]
+        cat ./test-results/$cmd^-^$input^-errors
+        cat ./test-results/$cmd^-^$input^-actual
+        do_exit
+    }
+    if (! diff ./test-results/$cmd^-^$input^-actual ./test-results/$cmd^-^$input^-expected >/dev/null) {
+        echo 'Incorrect output:' >[1=2]
+        echo '--- Any errors: ---' >[1=2]
+        cat ./test-results/$cmd^-^$input^-errors >[1=2]
+        echo '--- Diff: ---' >[1=2]
+        diff -c ./test-results/$cmd^-^$input^-actual ./test-results/$cmd^-^$input^-expected >[1=2] || true
+        do_exit
     }
     true
 }
