2012-12-26 gsac-deps tries to parse the matching .cgs file and complains if that file is completely empty (no #type pragma)

diff --git a/bin/test-fns b/bin/test-fns
--- a/bin/test-fns
+++ b/bin/test-fns
@@ -82,3 +82,22 @@ fn ok_grep_errors {
     }
     true
 }
+
+fn ok_grep_script_errors {
+    nm = $1; casenm=$2; msg=$3
+    shift; shift; shift
+    echo $nm
+    if ($* > ./test-results/$casenm^-actual >[2] ./test-results/$casenm^-errors) {
+        echo $* 'succeeded; should have failed' >[1=2]
+        cat ./test-results/$casenm^-errors >[1=2]
+        cat ./test-results/$casenm^-actual >[1=2]
+        exit 1
+    }
+    if (! grep -s $msg ./test-results/$casenm^-errors) {
+        echo 'Can''t find expected error message '''^$msg^''' in output anywhere' >[1=2]
+        cat ./test-results/$casenm^-errors >[1=2]
+        cat ./test-results/$casenm^-actual >[1=2]
+        exit 1
+    }
+    true
+}
