[tests] ok_script for just testing that a command succeeds

diff --git a/bin/test-fns b/bin/test-fns
--- a/bin/test-fns
+++ b/bin/test-fns
@@ -87,6 +87,21 @@ fn ok_grep_errors {
     true
 }
 
+fn ok_script {
+    nm=$1; casenm=$2
+    shift; shift
+    echo $nm
+    if (! $* > ./test-results/$casenm^-actual >[2] ./test-results/$casenm^-errors) {
+        echo 'The command' >[1=2]
+        echo '    ' $* >[1=2]
+        echo 'failed; should have succeeded' >[1=2]
+        cat ./test-results/$casenm^-errors >[1=2]
+        cat ./test-results/$casenm^-actual >[1=2]
+        exit 1
+    }
+    true
+}
+
 fn ok_diff_script {
     nm=$1; casenm=$2
     shift; shift
