2012-10-21 Check that the RHSs of .body generators have an appropriate type for the API monad the block statement is in

diff --git a/src/libglobalscript/rc/test b/src/libglobalscript/rc/test
--- a/src/libglobalscript/rc/test
+++ b/src/libglobalscript/rc/test
@@ -80,6 +80,19 @@ if (! grep -s './test-gslib/undef-expr-api.ags:11: undefined' ./test-results/und
 }
 echo
 
+echo '-- ''block'' statements with mis-typed bodies --'
+if (./$O.test-gsexec ./test-gslib ./test-gslib/mistyped-block-api.ags >[2] ./test-results/mistyped-block-api.ags-actual) {
+    echo 'test-gsexec succeeded; should have failed' >[1=2]
+    cat ./test-results/mistyped-block-api.ags-actual >[1=2]
+    exit 1
+}
+if (! grep -s './test-gslib/mistyped-block-api.ags:11: I don''t think' ./test-results/mistyped-block-api.ags-actual) {
+    echo 'Couldn''t find expected error message in output anywhere:' >[1=2]
+    cat ./test-results/mistyped-block-api.ags-actual >[1=2]
+    exit 1
+}
+echo
+
 echo '-- undefined ''block'' statement API entry points --'
 if (./$O.test-gsexec ./test-gslib ./test-gslib/undef-block-api.ags >[2] ./test-results/undef-block-api.ags-actual) {
     echo 'test-gsexec succeeded; should have failed' >[1=2]
