2012-10-16 Add support for lambdas, which are HNFs

diff --git a/src/libglobalscript/rc/test b/src/libglobalscript/rc/test
--- a/src/libglobalscript/rc/test
+++ b/src/libglobalscript/rc/test
@@ -24,6 +24,15 @@ if (./$O.test-gsi ./test-gslib ./test-gslib/undef-expr.ags > ./test-results/unde
 diff ./test-results/undef-expr.ags-actual ./test-results/undef-expr.ags-expected
 echo
 
+echo '-- lambdas with undefined bodies --'
+if (! ./$O.test-gsi ./test-gslib ./test-gslib/empty-lambda.ags > ./test-results/empty-lambda.ags-actual) {
+    echo 'test-gsi failed; should have succeeded' >[1=2]
+    cat ./test-results/empty-lambda.ags-actual
+    exit 1;
+}
+diff ./test-results/empty-lambda.ags-actual ./test-results/empty-lambda.ags-expected
+echo
+
 echo '-- undefined values of abstract types --'
 if (./$O.test-gsi ./test-gslib ./test-gslib/undef-abs-type.ags > ./test-results/undef-abs-type.ags-actual) {
     echo 'test-gsi succeeded; should have failed' >[1=2]
