2012-10-30 Add support for .record values with fields

diff --git a/src/libglobalscript/rc/test b/src/libglobalscript/rc/test
--- a/src/libglobalscript/rc/test
+++ b/src/libglobalscript/rc/test
@@ -78,7 +78,17 @@ if (! ./$O.test-gsi ./test-gslib ./test-gslib/rune-literal.ags > ./test-results/
     cat ./test-results/rune-literal.ags-actual >[1=2]
     exit 1
 }
-diff ./test-results/rune-literal.ags-actual ././test-results/rune-literal.ags-expected
+diff ./test-results/rune-literal.ags-actual ./test-results/rune-literal.ags-expected
+echo
+
+echo '-- non-empty records --'
+if (! ./$O.test-gsi ./test-gslib ./test-gslib/record-literal.ags > ./test-results/record-literal.ags-actual >[2] ./test-results/record-literal.ags-errors) {
+    echo 'test-gsi failed; should have succeeded' >[1=2]
+    cat ./test-results/record-literal.ags-errors >[1=2]
+    cat ./test-results/record-literal.ags-actual >[1=2]
+    exit 1
+}
+diff ./test-results/record-literal.ags-actual ./test-results/record-literal.ags-expected
 echo
 
 echo '-- undefined API entry points --'
