2012-10-30 Add polymorphic values, .enter, and enterring polymorphic values

diff --git a/src/libglobalscript/rc/test b/src/libglobalscript/rc/test
--- a/src/libglobalscript/rc/test
+++ b/src/libglobalscript/rc/test
@@ -1,5 +1,25 @@
 #! /usr/local/plan9/bin/rc -e
 
+fn ok_diff_fail {
+    echo $1
+    if ($2 ./test-gslib ./test-gslib/$3 > ./test-results/$3^-actual >[2] ./test-results/$3^-errors) {
+        echo $2 'succeeded; should have failed' >[1=2]
+        cat ./test-results/$3^-errors >[1=2]
+        cat ./test-results/$3^-actual >[1=2]
+        exit 1
+    }
+    if (! diff ./test-results/$3^-actual ./test-results/$3^-expected) {
+        echo $2 'produced incorrect output' >[1=2]
+        echo '--- Actual ---' >[1=2]
+        cat ./test-results/$3^-errors >[1=2]
+        cat ./test-results/$3^-actual >[1=2]
+        echo '--- Expected ---' >[1=2]
+        cat ./test-results/$3^-expected
+        exit 1
+    }
+    true
+}
+
 echo '-- undefined entry points --'
 if (./$O.test-gsi ./test-gslib ./test-gslib/undef.ags > ./test-results/undef.ags-actual) {
     echo 'test-gsi succeeded; should have failed' >[1=2]
@@ -40,6 +60,8 @@ if (./$O.test-gsi ./test-gslib ./test-gslib/undef-expr.ags > ./test-results/unde
 }
 diff ./test-results/undef-expr.ags-actual ./test-results/undef-expr.ags-expected
 echo
+
+ok_diff_fail '-- enter undefined polymorphic value --' ./$O.test-gsi enter-polymorphic-undef.ags
 
 echo '-- lambdas with undefined bodies --'
 if (! ./$O.test-gsi ./test-gslib ./test-gslib/empty-lambda.ags > ./test-results/empty-lambda.ags-actual) {
