2012-10-27 Add support for rune literals

diff --git a/src/libglobalscript/rc/test b/src/libglobalscript/rc/test
--- a/src/libglobalscript/rc/test
+++ b/src/libglobalscript/rc/test
@@ -71,6 +71,16 @@ if (! grep -s './test-gslib/invalid-abs-type.ags:[0-9]*: I don''t think' ./test-
 }
 echo
 
+echo '-- rune literals --'
+if (! ./$O.test-gsi ./test-gslib ./test-gslib/rune-literal.ags > ./test-results/rune-literal.ags-actual >[2] ./test-results/rune-literal.ags-errors) {
+    echo 'test-gsi failed; should have succeeded' >[1=2]
+    cat ./test-results/rune-literal.ags-errors >[1=2]
+    cat ./test-results/rune-literal.ags-actual >[1=2]
+    exit 1
+}
+diff ./test-results/rune-literal.ags-actual ././test-results/rune-literal.ags-expected
+echo
+
 echo '-- undefined API entry points --'
 if (./$O.test-gsexec ./test-gslib ./test-gslib/undef-api.ags >[2] ./test-results/undef-api.ags-actual) {
     echo 'test-gsexec succeeded; should have failed' >[1=2]
