2012-10-31 Add support for lifted function literals

diff --git a/src/libglobalscript/rc/test b/src/libglobalscript/rc/test
--- a/src/libglobalscript/rc/test
+++ b/src/libglobalscript/rc/test
@@ -1,5 +1,25 @@
 #! /usr/local/plan9/bin/rc -e
 
+fn ok_diff {
+    echo $1
+    if (! $2 ./test-gslib ./test-gslib/$3 > ./test-results/$3^-actual >[2] ./test-results/$3^-errors) {
+        echo $2 'failed; should have succeeded' >[1=2]
+        cat ./test-results/$3^-errors >[1=2]
+        cat ./test-results/$3^-actual >[1=2]
+        exit 1
+    }
+    if (! diff ./test-results/$3^-actual ./test-results/$3^-expected) {
+        echo $2 'produced incorrect output' >[1=2]
+        echo '--- Actual ---' >[1=2]
+        cat ./test-results/$3^-errors >[1=2]
+        cat ./test-results/$3^-actual >[1=2]
+        echo '--- Expected ---' >[1=2]
+        cat ./test-results/$3^-expected
+        exit 1
+    }
+    true
+}
+
 fn ok_diff_fail {
     echo $1
     if ($2 ./test-gslib ./test-gslib/$3 > ./test-results/$3^-actual >[2] ./test-results/$3^-errors) {
@@ -71,6 +91,8 @@ if (! ./$O.test-gsi ./test-gslib ./test-gslib/empty-lambda.ags > ./test-results/
 }
 diff ./test-results/empty-lambda.ags-actual ./test-results/empty-lambda.ags-expected
 echo
+
+ok_diff '-- lifted lambdas with undefined bodies --' ./$O.test-gsi empty-lifted-lambda.ags
 
 echo '-- undefined values of abstract types --'
 if (./$O.test-gsi ./test-gslib ./test-gslib/undef-abs-type.ags > ./test-results/undef-abs-type.ags-actual) {
