2012-10-20 Add expression support to API; this also involves tracking when all threads blocked so we can insert a sleep, which complicates things

diff --git a/src/libglobalscript/rc/test b/src/libglobalscript/rc/test
--- a/src/libglobalscript/rc/test
+++ b/src/libglobalscript/rc/test
@@ -60,7 +60,20 @@ if (./$O.test-gsexec ./test-gslib ./test-gslib/undef-api.ags >[2] ./test-results
     exit 1
 }
 if (! grep -s './test-gslib/undef-api.ags:5: undefined' ./test-results/undef-api.ags-actual) {
-    echo 'Couldn''t find expected error message in output anywhere' >[1=2]
+    echo 'Couldn''t find expected error message in output anywhere:' >[1=2]
+    cat ./test-results/undef-api.ags-actual >[1=2]
+    exit 1
+}
+echo
+
+echo '-- undefined expression API entry points --'
+if (./$O.test-gsexec ./test-gslib ./test-gslib/undef-expr-api.ags >[2] ./test-results/undef-expr-api.ags-actual) {
+    echo 'test-gsexec succeeded; should have failed' >[1=2]
+    exit 1
+}
+if (! grep -s './test-gslib/undef-expr-api.ags:11: undefined' ./test-results/undef-expr-api.ags-actual) {
+    echo 'Couldn''t find expected error message in output anywhere:' >[1=2]
+    cat ./test-results/undef-expr-api.ags-actual >[1=2]
     exit 1
 }
 echo
