2012-09-13 Add support for (undefined values of) empty product types

diff --git a/src/libglobalscript/rc/test b/src/libglobalscript/rc/test
--- a/src/libglobalscript/rc/test
+++ b/src/libglobalscript/rc/test
@@ -1,7 +1,17 @@
 #! /usr/local/plan9/bin/rc -e
 
+echo '-- undefined entry points --'
 if (./$O.test-gsi ./test-gslib ./test-gslib/undef.ags > ./test-results/undef.ags-actual) {
-    echo test-gsi succeeded >[1=2]
+    echo 'test-gsi succeeded; should have failed' >[1=2]
     exit 1
 }
 diff ./test-results/undef.ags-actual ./test-results/undef.ags-expected
+echo
+
+echo '-- undefined empty record values --'
+if (./$O.test-gsi ./test-gslib ./test-gslib/undef-empty-record.ags > ./test-results/undef-empt-record.ags-actual) {
+    echo 'test-gsi succeeded; should have failed' >[1=2]
+    exit 1
+}
+diff ./test-results/undef-empt-record.ags-actual ./test-results/undef-empt-record.ags-expected
+echo
